CREATE OR REPLACE VIEW <#= ObjectView #> AS
SELECT
-- This code was generated by <#= TemplateName #> @ <#= DateTime.Now.ToString() #>
<#= ColumnListClause #>
FROM
<#= JoinClause #>
WITH READ ONLY;
