-- =============================================
-- Script Template
-- =============================================
IF NOT EXISTS (SELECT 1 FROM T4SQL.ENGINE_CONFIG WHERE ELEMENT_NAME = 'POLL_INTERVAL')
INSERT INTO T4SQL.ENGINE_CONFIG (ELEMENT_NAME, NUMBER_VALUE, DATE_VALUE, STRING_VALUE, DESCRIPTION_)
VALUES ('POLL_INTERVAL', 1, null, '', 'Engine Polling Interval (Seconds).');

IF NOT EXISTS (SELECT 1 FROM T4SQL.ENGINE_CONFIG WHERE ELEMENT_NAME = 'STANDBY_BEAT')
INSERT INTO T4SQL.ENGINE_CONFIG (ELEMENT_NAME, NUMBER_VALUE, DATE_VALUE, STRING_VALUE, DESCRIPTION_)
VALUES ('STANDBY_BEAT', null, '2013-01-01', '', 'Heartbeat of Standby Pump Service.');

IF NOT EXISTS (SELECT 1 FROM T4SQL.ENGINE_CONFIG WHERE ELEMENT_NAME = 'PRIMARY_BEAT')
INSERT INTO T4SQL.ENGINE_CONFIG (ELEMENT_NAME, NUMBER_VALUE, DATE_VALUE, STRING_VALUE, DESCRIPTION_)
VALUES ('PRIMARY_BEAT', null, '2013-01-01', '', 'Heartbeat of Primary Pump Service.');
