-- =============================================
-- Script Template
-- =============================================
IF NOT EXISTS (SELECT 1 FROM T4SQL.WORKSPACE_ENTRY WHERE WORKSPACE_SCHEMA = N'T4SQL' AND WORKITEM_TABLE_NAME = N'SEED_WORKITEM' AND PROPERTY_TABLE_NAME = N'SEED_PROPERTY')
INSERT INTO T4SQL.WORKSPACE_ENTRY
(
	WORKSPACE_SCHEMA,
	WORKITEM_TABLE_NAME,
	PROPERTY_TABLE_NAME,
	AUTONOMOUS_OWNER,
	WORKSPACE_DESCRIPTION
)
VALUES
(
	N'T4SQL',
	N'SEED_WORKITEM',
	N'SEED_PROPERTY',
	N'SYS',
	N'(Built-in)SEED WORKSPACE'
);
