-- =============================================
-- Script Template
-- =============================================
IF NOT EXISTS (SELECT 1 FROM T4SQL.WORKSPACE_ENTRY WHERE OBJECT_ID(WORKITEM_TABLE_NAME, N'U') = OBJECT_ID(N'T4SQL.SEED_WORKITEM') AND OBJECT_ID(PROPERTY_TABLE_NAME) = OBJECT_ID(N'T4SQL.SEED_PROPERTY'))
INSERT INTO T4SQL.WORKSPACE_ENTRY
(
	WORKITEM_TABLE_NAME,
	PROPERTY_TABLE_NAME,
	AUTONOMOUS_OWNER,
	WORKSPACE_DESCRIPTION
)
VALUES
(
	N'T4SQL.SEED_WORKITEM',
	N'T4SQL.SEED_PROPERTY',
	N'SYS',
	N'(Built-in)SEED WORKSPACE'
);
