IF OBJECT_ID(N'<#= ObjectView #>', N'V') IS NULL
	EXECUTE ('CREATE VIEW <#= ObjectView #> AS SELECT NULL AS CREATE_OR_REPLACE');
GO

ALTER VIEW <#= ObjectView #> AS
-- This code was generated by <#= TemplateName #> @ <#= DateTime.Now.ToString() #>
<#
	if (DbmsVersion > new Version(11, 0))	// SQL Server 2012
	{
#>
SELECT
	D.<#= DailyDateColumn #><#= SelectColumns.Select(c => "S." + c).InsertRight() #>
FROM
	(
		SELECT
			<#= SelectColumns.InsertLeft() #>
			<#= SourceDateColumn #>		AS START$DATE,
			LEAD(<#= SourceDateColumn #>, 1, CAST('2999-12-31' AS DATE)) OVER (PARTITION BY <#= Key_Columns #> ORDER BY <#= SourceDateColumn #>)
										AS EXPIRE$DATE
		FROM
			<#= SourceView #>
	)	S,
	<#= DailyView #>	D
WHERE
		S.EXPIRE$DATE > D.<#= DailyDateColumn #>
	AND S.START$DATE <= D.<#= DailyDateColumn #>
<#
	}
	else									// SQL Server 2008, 2005
	{
#>
WITH TR AS
(
	SELECT
		*,
		ROW_NUMBER() OVER (PARTITION BY <#= Key_Columns #> ORDER BY <#= SourceDateColumn #>) AS ROW$NUMBER
	FROM
		<#= SourceView #>
)
SELECT
	D.<#= DailyDateColumn #><#= SelectColumns.Select(c => "S." + c).InsertRight() #>
FROM
	(
		SELECT
			<#= SelectColumns.Select(c => "t1." + c).InsertLeft() #>
			t1.<#= SourceDateColumn #>											AS START$DATE,
			ISNULL(t2.<#= SourceDateColumn #>, CAST('2999-12-31' AS DATE))		AS EXPIRE$DATE
		FROM
			TR t1 LEFT OUTER JOIN
			TR t2 ON (<#= String.Join(" AND ", KeyColumns.Select(k => string.Format(@"t1.{0} = t2.{0}", k))) #>
				AND t1.ROW$NUMBER + 1 = t2.ROW$NUMBER)
	)	S,
	<#= DailyView #>	D
WHERE
		S.EXPIRE$DATE > D.<#= DailyDateColumn #>
	AND S.START$DATE <= D.<#= DailyDateColumn #>
<#
	}
#>
;
GO

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		May 15, 2013, 11:25:04 PM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------
