CREATE OR REPLACE VIEW <#= ObjectView #> AS
SELECT
	-- This code was generated by <#= TemplateName #> @ <#= DateTime.Now.ToString() #>
	D.<#= DailyDateColumn #><#= SelectColumns.Select(c => "S." + c).InsertRight() #>
FROM
	(
		SELECT
			<#= SelectColumns.InsertLeft() #>
			<#= SourceDateColumn #>		AS START$DATE,
			LEAD(<#= SourceDateColumn #>, 1, TO_DATE('2999-12-31', 'YYYY-MM-DD')) OVER (PARTITION BY <#= Key_Columns #> ORDER BY <#= SourceDateColumn #>)
										AS EXPIRE$DATE
		FROM
			<#= SourceView #>
	)	S,
	<#= DailyView #>	D
WHERE
		S.EXPIRE$DATE > D.<#= DailyDateColumn #>
	AND S.START$DATE <= D.<#= DailyDateColumn #>

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		May 15, 2013, 11:25:04 PM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------
