CREATE OR REPLACE VIEW <#= ObjectView #> AS
SELECT
-- This code was generated by <#= TemplateName #> @ <#= DateTime.Now.ToString() #>
<#
	string tEndDateCol = IsEndDateNext ? DateColumn : string.Format("({0} - 1)", DateColumn);
#>
	<#= SelectColumns.InsertLeft() #>
	<#= DateColumn #>		AS <#= RangeStartDateColumn #>,
	LEAD(<#= tEndDateCol #>, 1<#= DefaultEndDate.IsNullString() ? "" : ", " + DefaultEndDate #>) OVER (PARTITION BY <#= Key_Columns #> ORDER BY <#= DateColumn #>)
								AS <#= RangeEndDateColumn #>
FROM
	<#= SourceView #>

WITH READ ONLY;
