CREATE OR REPLACE VIEW <#= ObjectView #> AS
SELECT
	-- This code was generated by <#= TemplateName #> @ <#= DateTime.Now.ToString() #>
	<#= KeyColumns #>,
	MIN(<#= RangeStartDateColumn #>)									AS <#= RangeStartDateColumn #>,
	MAX(NVL(<#= RangeEndDateColumn #>, <#= DefaultEndDate #>))	AS <#= RangeEndDateColumn #>,
	(MAX(NVL(<#= RangeEndDateColumn #>, <#= DefaultEndDate #>)) - MIN(<#= RangeStartDateColumn #>))<#= IsEndDateNext ? "" : " + 1" #>	AS <#= InscopeDaysColumn #>,
	SUM((NVL(<#= RangeEndDateColumn #>, <#= DefaultEndDate #>) - <#= RangeStartDateColumn #>)<#= IsEndDateNext ? "" : " + 1" #>)		AS <#= CheckSumColumn #>
FROM
	<#= SourceView #>
GROUP BY
	<#= KeyColumns #>

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		June 02, 2013, 11:00:30 AM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------
