INSERT INTO T4SQL.WORKSPACE_ENTRY
(
	WORKITEM_TABLE_NAME,
	PROPERTY_TABLE_NAME,
	AUTONOMOUS_OWNER,
	WORKSPACE_DESCRIPTION
)
VALUES
(
	'T4SQL.SEED_WORKITEM',
	'T4SQL.SEED_PROPERTY',
	'SYS',
	'(Built-in)SEED WORKSPACE'
);

COMMIT;
