GRANT SELECT ANY TABLE TO T4SQL;
GRANT CREATE ANY TABLE TO T4SQL;
GRANT CREATE ANY INDEX TO T4SQL;
GRANT CREATE ANY VIEW TO T4SQL;
GRANT CREATE ANY TRIGGER TO T4SQL;

GRANT EXECUTE ON SYS.DBMS_LOCK TO T4SQL;
