GRANT SELECT ON T4SQL.UTL_ORDINAL_NUMBER TO PUBLIC;
GRANT SELECT ON T4SQL.VW_ORDINAL_DATE TO PUBLIC;
GRANT SELECT ON T4SQL.VW_ORDINAL_NUMBER_EXPANSION TO PUBLIC;
GRANT SELECT ON T4SQL.TEMPLATE_CLASS TO PUBLIC;
GRANT SELECT ON T4SQL.TEMPLATE_SPEC TO PUBLIC;

GRANT REFERENCES ON T4SQL.TEMPLATE_CLASS TO PUBLIC;
GRANT EXECUTE ON T4SQL.PUB_REF TO PUBLIC;
