IF OBJECT_ID(N'<#= ObjectView #>', N'V') IS NULL
	EXECUTE ('CREATE VIEW <#= ObjectView #> AS SELECT NULL AS CREATE_OR_REPLACE');
GO

ALTER VIEW <#= ObjectView #> AS
-- This code was generated by <#= TemplateName #> @ <#= DateTime.Now.ToString() #>
WITH
	CTE_MAIN AS
	(
		SELECT
			<#= Junction_Columns #>,
			<#= PivotColumn #>,
			<#= MeasureColumn #>
		FROM
			<#= SourceView #>
		WHERE
			<#= PivotColumn #>	IN (<#= Value_List #>)
			<#= SourceFilter.InsertRight("AND	") #>
	),
	JOIN_ON AS
	(
		SELECT DISTINCT
			<#= Junction_Columns #>
		FROM
			CTE_MAIN
	)
<#
	for (int i = 0; i < Value_Aliases.Length; i++)
	{
#>
	,
	CTE_<#= i #>	AS
	(
		SELECT
			<#= Junction_Columns #>,
			<#= MeasureColumn #>
		FROM
			CTE_MAIN
		WHERE
			<#= PivotColumn #>	= <#= Value_Aliases[i].Item1 #>
	)
<#
	}
#>
SELECT
	J.<#= Junction_Columns #>
<#
	for (int i = 0; i < Value_Aliases.Length; i++)
	{
#>
	, C<#= i #>.<#= MeasureColumn #>		AS <#= Value_Aliases[i].Item2 #>
<#
	}
#>
FROM
	JOIN_ON		J
<#
	for (int i = 0; i < Value_Aliases.Length; i++)
	{
#>
	LEFT JOIN
	CTE_<#= i #>		C<#= i #>
	ON	(<#= string.Join(" AND ", JunctionColumns.Select(c => string.Format("J.{0} = C{1}.{0}", c, i))) #>)
<#
	}
#>
;
GO

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		November 26, 2013, 10:06:19 PM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------
