CREATE OR REPLACE VIEW <#= ObjectView #> AS
SELECT
-- This code was generated by <#= TemplateName #> @ <#= DateTime.Now.ToString() #>
	T.*
<#
	if (!string.IsNullOrWhiteSpace(KeyColumns))
	{
		if (!string.IsNullOrWhiteSpace(OrderBy) && !string.IsNullOrWhiteSpace(RowNumberAlias))
		{
#>
	, ROW_NUMBER() OVER (PARTITION BY <#= KeyColumns #> ORDER BY <#= OrderBy #>) AS <#= RowNumberAlias #>
<#
		}

		if (!string.IsNullOrWhiteSpace(CountAlias))
		{
#>
	, COUNT(*) OVER (PARTITION BY <#= KeyColumns #>) AS <#= CountAlias #>
<#
		}
	}
#>
<#= RowidAlias.InsertRight("	, T.ROWID AS ") #>
FROM
	<#= SourceTable #>	T
<#= SourceFilter.InsertRight("WHERE\r\n	") #>
WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		January 13, 2014, 11:00:42 PM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------
