CREATE OR REPLACE TRIGGER TRG_WORKSPACE_ENTRY_DEL
BEFORE DELETE ON T4SQL.WORKSPACE_ENTRY
FOR EACH ROW
BEGIN
	IF :old.WORKITEM_TABLE_NAME = 'T4SQL.SEED_WORKITEM' AND :old.PROPERTY_TABLE_NAME = 'T4SQL.SEED_PROPERTY' THEN
		RAISE_APPLICATION_ERROR(-21001, 'Built-in workspace T4SQL.SEED_... cannot be deleted!');
	END IF;
END;
/
