------------------ Started at: 2013-12-07 23:50:27 ------------------

------------------ Build started workitem: testVTimePointsToRanges ------------------
CREATE OR REPLACE VIEW test.vw_timepoints_ranges AS
SELECT
	-- This code was generated by T4SQL.Date.VTimePointsToRanges @ 12/7/2013 11:50:27 PM
	catalog_id, position_id, VALUE_, OTHER_COL, 
	DATE_		AS START_DATE,
	LEAD((DATE_ - 1), 1, TO_DATE('2999-12-31', 'YYYY-MM-DD')) OVER (PARTITION BY catalog_id, position_id ORDER BY DATE_)
								AS END_DATE
FROM
	test.date_time_points

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		May 20, 2013, 12:00:44 AM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVTimePointsToRanges ------------------

------------------ Build started workitem: testVTimeRangesToSeries ------------------
CREATE OR REPLACE VIEW test.vw_timeranges_series AS
SELECT
	-- This code was generated by T4SQL.Date.VTimeRangesToSeries @ 12/7/2013 11:50:27 PM
	D.DATE_, S.CATALOG_ID, S.POSITION_ID, S.VALUE_, S.OTHER_COL
FROM
	test.vw_timepoints_ranges	S,
	T4SQL.VW_ORDINAL_DATE	D
WHERE
	(
		S.END_DATE >= D.DATE_
		OR S.END_DATE IS NULL
	)
	AND S.START_DATE <= D.DATE_

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		May 15, 2013, 11:27:30 PM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVTimeRangesToSeries ------------------

------------------ Build started workitem: testVTimePointsToSeries ------------------
CREATE OR REPLACE VIEW test.vw_timepoints_series AS
SELECT
	-- This code was generated by T4SQL.Date.VTimePointsToSeries @ 12/7/2013 11:50:27 PM
	D.DATE_, S.catalog_id, S.position_id, S.VALUE_, S.OTHER_COL
FROM
	(
		SELECT
			catalog_id, position_id, VALUE_, OTHER_COL, 
			DATE_		AS START$DATE,
			LEAD(DATE_, 1, TO_DATE('2999-12-31', 'YYYY-MM-DD')) OVER (PARTITION BY catalog_id, position_id ORDER BY DATE_)
										AS EXPIRE$DATE
		FROM
			test.date_time_points
	)	S,
	T4SQL.VW_ORDINAL_DATE	D
WHERE
		S.EXPIRE$DATE > D.DATE_
	AND S.START$DATE <= D.DATE_

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		May 15, 2013, 11:25:04 PM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVTimePointsToSeries ------------------

------------------ Build started workitem: testVTimeSeriesToRanges ------------------
CREATE OR REPLACE VIEW test.vw_timeseries_ranges AS
SELECT
	-- This code was generated by T4SQL.Date.VTimeSeriesToRanges @ 12/7/2013 11:50:27 PM
	CATALOG_ID, POSITION_ID, VALUE_, OTHER_COL, 
	MIN(DATE_)		AS START_DATE,
	MAX(DATE_)		AS END_DATE
FROM
	test.vw_timepoints_series
GROUP BY
	CATALOG_ID, POSITION_ID, VALUE_, OTHER_COL

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		May 19, 2013, 11:59:23 PM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVTimeSeriesToRanges ------------------

------------------ Build started workitem: testVTimeRangesCheckSum ------------------
CREATE OR REPLACE VIEW test.vw_timeranges_chksum AS
SELECT
	-- This code was generated by T4SQL.Date.VTimeRangesCheckSum @ 12/7/2013 11:50:27 PM
	catalog_id, position_id,
	MIN(START_DATE)									AS START_DATE,
	MAX(NVL(END_DATE, TRUNC(SYSDATE)))	AS END_DATE,
	(MAX(NVL(END_DATE, TRUNC(SYSDATE))) - MIN(START_DATE)) + 1	AS INSCOPE_DAYS,
	SUM((NVL(END_DATE, TRUNC(SYSDATE)) - START_DATE) + 1)		AS CHECK_SUM
FROM
	test.vw_timepoints_ranges
GROUP BY
	catalog_id, position_id

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		June 02, 2013, 11:00:30 AM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVTimeRangesCheckSum ------------------

------------------ Build started workitem: testVPivot ------------------
CREATE OR REPLACE VIEW test.vw_pivot AS
SELECT
	-- This code was generated by T4SQL.Pivot.VPivot @ 12/7/2013 11:50:27 PM
	*
FROM
(
	SELECT
		product_id, value_, attrib_code
	FROM
		test.pivot_discrete_attrib
	
)	S
PIVOT
(
	MAX(value_)
	FOR attrib_code IN ('FIELD_A' AS V_A, 'FIELD_B' AS V_B, 'FIELD_C' AS V_C, 'FIELD_D' as V_D, 'FIELD_E' as V_E, 'FIELD_F' as V_F, 'FIELD_G' as V_G, 'FIELD_H' as V_H)
)	P

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		June 02, 2013, 11:06:09 AM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVPivot ------------------

------------------ Build started workitem: testVUnpivot ------------------
CREATE OR REPLACE VIEW test.vw_unpivot AS
SELECT
	-- This code was generated by T4SQL.Pivot.VUnpivot @ 12/7/2013 11:50:27 PM
	product_id, attrib_code, value_
FROM
	test.vw_pivot
UNPIVOT
(
	value_ FOR attrib_code IN
	(
		V_A as 'FIELD_A', V_B as 'FIELD_B', V_C as 'FIELD_C', V_D, V_E, V_F, V_G, V_H
	)
)	U

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		June 02, 2013, 11:06:37 AM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVUnpivot ------------------

------------------ Build started workitem: testVGroupingSets ------------------
CREATE OR REPLACE VIEW test.vw_grouping_sets AS
SELECT
	-- This code was generated by T4SQL.Grouping.VGroupingSets @ 12/7/2013 11:50:27 PM
	simulation_id, 
	CASE GROUPING_ID(is_cash, prod_code, grp1_type, grp2_code, grp3_class)
		WHEN 31	THEN 'TOTAL_FUND'
		WHEN 15	THEN 'AGG_CASH'
		WHEN 7	THEN 'AGG_PROD'
		WHEN 25	THEN 'agg_grp12'
		WHEN 28	THEN 'agg_grp23'
	END		AS AGG_TYPE,
	is_cash, prod_code, grp1_type, grp2_code, grp3_class,
	SUM(value1) AS SUM_V1, SUM(value2) AS SUM_V2, SUM(value3) AS SUM_V3, SUM(value4) AS SUM_V4
FROM
	test.grouping_flat_values

GROUP BY
	simulation_id, 
	GROUPING SETS
	(
		(), (is_cash), (is_cash, prod_code), (grp1_type, grp2_code), (grp2_code, grp3_class)
	)

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		June 14, 2013, 12:24:41 AM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVGroupingSets ------------------

------------------ Build started workitem: testVNaviForeignKey ------------------
CREATE OR REPLACE VIEW test.vw_navi_grp_flat AS
SELECT
	-- This code was generated by T4SQL.Assoc.VNaviForeignKey @ 12/7/2013 11:50:27 PM
	A.SIMULATION_ID,
	A.POSITION_ID,
	A.IS_CASH,
	A.PROD_CODE,
	A.GRP1_TYPE,
	A.GRP2_CODE,
	A.GRP3_CLASS,
	A.VALUE1,
	A.VALUE2,
	A.VALUE3,
	A.VALUE4,
	AA.DESCRIPTION_,
	AB.PROD_NAME,
	AC.SIM_DESC,
	AC.SIM_TYPE,
	AC.CREATED_TIME,
	AC.CREATOR,
	ACA.SIM_TYPE_DESC
FROM
	TEST.GROUPING_FLAT_VALUES A
	INNER JOIN
		TEST.PROD_TYPE AB
	ON (A.PROD_CODE = AB.PROD_CODE)
	INNER JOIN (
		TEST.SIMULATION AC
		INNER JOIN
			TEST.SIM_TYPE ACA
		ON (AC.SIM_TYPE = ACA.SIM_TYPE_ID)
	) ON (A.SIMULATION_ID = AC.ID_)
	LEFT JOIN
		TEST.GRP3_CLASS AA
	ON (A.GRP3_CLASS = AA.GRP3_CLASS)

WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		July 03, 2013, 12:56:08 AM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVNaviForeignKey ------------------

------------------ Build started workitem: testVFullPivot ------------------
CREATE OR REPLACE VIEW test.vw_full_pivot AS
WITH
-- This code was generated by T4SQL.Pivot.VFullPivot @ 12/7/2013 11:50:28 PM
	CTE_MAIN AS
	(
		SELECT
			product_id,
			attrib_code,
			value_
		FROM
			test.pivot_discrete_attrib
		WHERE
			attrib_code	IN ('FIELD_A', 'FIELD_B', 'FIELD_C', 'FIELD_D', 'FIELD_E', 'FIELD_F', 'FIELD_G', 'FIELD_H')
			
	),
	JOIN_ON AS
	(
		SELECT DISTINCT
			product_id
		FROM
			CTE_MAIN
	)
	,
	CTE_0	AS
	(
		SELECT
			product_id,
			value_
		FROM
			CTE_MAIN
		WHERE
			attrib_code	= 'FIELD_A'
	)
	,
	CTE_1	AS
	(
		SELECT
			product_id,
			value_
		FROM
			CTE_MAIN
		WHERE
			attrib_code	= 'FIELD_B'
	)
	,
	CTE_2	AS
	(
		SELECT
			product_id,
			value_
		FROM
			CTE_MAIN
		WHERE
			attrib_code	= 'FIELD_C'
	)
	,
	CTE_3	AS
	(
		SELECT
			product_id,
			value_
		FROM
			CTE_MAIN
		WHERE
			attrib_code	= 'FIELD_D'
	)
	,
	CTE_4	AS
	(
		SELECT
			product_id,
			value_
		FROM
			CTE_MAIN
		WHERE
			attrib_code	= 'FIELD_E'
	)
	,
	CTE_5	AS
	(
		SELECT
			product_id,
			value_
		FROM
			CTE_MAIN
		WHERE
			attrib_code	= 'FIELD_F'
	)
	,
	CTE_6	AS
	(
		SELECT
			product_id,
			value_
		FROM
			CTE_MAIN
		WHERE
			attrib_code	= 'FIELD_G'
	)
	,
	CTE_7	AS
	(
		SELECT
			product_id,
			value_
		FROM
			CTE_MAIN
		WHERE
			attrib_code	= 'FIELD_H'
	)
SELECT
	J.product_id
	, C0.value_		AS V_A
	, C1.value_		AS V_B
	, C2.value_		AS V_C
	, C3.value_		AS V_D
	, C4.value_		AS V_E
	, C5.value_		AS V_F
	, C6.value_		AS V_G
	, C7.value_		AS V_H
FROM
	JOIN_ON		J
	LEFT JOIN
	CTE_0		C0
	ON	(J.product_id = C0.product_id)
	LEFT JOIN
	CTE_1		C1
	ON	(J.product_id = C1.product_id)
	LEFT JOIN
	CTE_2		C2
	ON	(J.product_id = C2.product_id)
	LEFT JOIN
	CTE_3		C3
	ON	(J.product_id = C3.product_id)
	LEFT JOIN
	CTE_4		C4
	ON	(J.product_id = C4.product_id)
	LEFT JOIN
	CTE_5		C5
	ON	(J.product_id = C5.product_id)
	LEFT JOIN
	CTE_6		C6
	ON	(J.product_id = C6.product_id)
	LEFT JOIN
	CTE_7		C7
	ON	(J.product_id = C7.product_id)
WITH READ ONLY;

----------------------------------------------------------------------------------------------------
--
--	Copyright 2013 Abel Cheng
--	This source code is subject to terms and conditions of the Apache License, Version 2.0.
--	See http://www.apache.org/licenses/LICENSE-2.0.
--	All other rights reserved.
--	You must not remove this notice, or any other, from this software.
--
--	Original Author:	Abel Cheng <abelcys@gmail.com>
--	Created Date:		November 26, 2013, 10:06:19 PM
--	Primary Host:		http://t4sql.codeplex.com
--	Change Log:
--	Author				Date			Comment
--
--
--
--
--	(Keep code clean)
--
----------------------------------------------------------------------------------------------------


------------------ Build ended - workitem: testVFullPivot ------------------

------------------ Build Total: 10 Workitems. Ended at: 2013-12-07 23:50:33 ------------------
